dist: trusty
language: java
services: docker
sudo: false
group: edge
before_install:
    - chmod +x .travis/script.sh
    - echo "MAVEN_OPTS='-Xmx384m'" > ~/.mavenrc
install:
    # generate SSL certificates
    - mkdir tmp
    - .travis/gen-ssl.sh mariadb.example.com tmp
    - chmod 777 tmp
    - chmod 777 tmp/*
    - ls -lrt tmp
#cache:
#  directories:
#    - $HOME/.m2

jdk:
#    - oraclejdk9
    - oraclejdk8

env:
#    - AURORA=true
#    - DB=mysql:5.5 PACKET=8M
#    - DB=mysql:5.6 PACKET=8M
#    - DB=mysql:5.7 PACKET=8M
#    - DB=mysql:8.0 PACKET=8M
#    - DB=mariadb:5.5 PACKET=8M
#    - DB=mariadb:10.0 PACKET=8M
#    - DB=mariadb:10.1 PACKET=8M
    - DB=mariadb:10.2 PACKET=8M
#    - DB=mariadb:10.2 PACKET=8M PROFILE=true
#    - DB=mariadb:10.2 PACKET=8M TYPE=PREPARE
#    - DB=mariadb:10.2 PACKET=8M TYPE=REWRITE
#    - DB=mariadb:10.2 PACKET=8M TYPE=MULTI
#    - DB=mariadb:10.2 PACKET=20M
#    - DB=mariadb:10.2 PACKET=40M
#    - DB=mariadb:10.2 PACKET=40M TYPE=BULK_SERVER
#    - DB=mariadb:10.2 PACKET=40M TYPE=NO_BULK_CLIENT
#    - DB=mariadb:10.2 PACKET=40M TYPE=NO_BULK_SERVER
#    - DB=mariadb:10.2 PACKET=40M COMPRESSION=true
#    - DB=mariadb:10.3 PACKET=8M
#    - DB=mariadb:10.2 PACKET=8M MAXSCALE_VERSION=2.0.2
#    - DB=mariadb:10.2 PACKET=8M MAXSCALE_VERSION=2.0.6
#    - DB=mariadb:10.2 PACKET=8M MAXSCALE_VERSION=2.1.4
script: .travis/script.sh
